# Semantic Release Configuration
# https://semantic-release.gitbook.io/semantic-release/usage/configuration

# Any merges into branches that match these patterns will trigger a release.
branches:
  - name: main
  - name: "1.26.x"
    prerelease: false

# These plugins will run when a release is triggered. They will analyze commit
# messages to determine what kind of release this is and publish a new release.
plugins:
  # Analyze commit messages to determine next version
  - "@semantic-release/commit-analyzer"

  # Generate release notes
  - "@semantic-release/release-notes-generator"

  # Replace version strings in the project. The 'git' plugin is needed to
  # commit the version strings to the repository.
  - - "@google/semantic-release-replace-plugin"
    - replacements:
        - files:
            - SteamBus.App/SteamBus.csproj
          from: "^<Version>.*</Version>$"
          to: "<Version>${nextRelease.version}</Version>"
        - files:
            - SteamBus.App/steam-bus.spec
          from: "^Version: .*$"
          to: "Version: ${nextRelease.version}"

  # Execute commands to build the project
  - - "@semantic-release/exec"
    - shell: true
      prepareCmd: |
        make in-docker TARGET='tar rpm'
        make in-docker TARGET='tar rpm' ARCH="aarch64"
      publishCmd: "echo '${nextRelease.version}' > .version.txt"

  # Commit the following changes to git after other plugins have run
  - - "@semantic-release/git"
    - assets:
        - SteamBus.App/SteamBus.csproj
        - SteamBus.App/steam-bus.spec

  # Publish artifacts as a GitHub release
  - - "@semantic-release/github"
    - assets:
        - path: SteamBus-*.rpm
        - path: SteamBus-*.tar.gz
